services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./backendSKKMigas:/app/backendSKKMigas
    environment:
      - PYTHONUNBUFFERED=1
      - SQLALCHEMY_DATABASE_URL=sqlite:///./test.db
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/backendSKKMigas/frontend
      - /backendSKKMigas/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend