FROM node:20-alpine
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN chown -R node:node /app
USER node

# Start the app in development mode for hot-reloading
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]