from sqlalchemy.orm import relationship, declared_attr
from sqlalchemy import Column, String, Integer, ForeignKey, DateTime, Numeric, JSON, Enum, Text, Boolean, Float
from enum import Enum as PyEnum
from app.database import Base

class Well(Base):
    
    __tablename__ = 'wells'
    
    
    UWI = Column(String, primary_key=True)
    ALT_WELL_NAME = Column(String)
    AOF_COUNT = Column(Integer)
    ASSIGNED_FIELD = Column(String)
    BASIN = Column(String)
    BOTTOM_HOLE_LATITUDE = Column(Float)
    BOTTOM_HOLE_LOC_QUALITY = Column(String)
    BOTTOM_HOLE_LONGITUDE = Column(Float)
    COMPLETION_DATE = Column(DateTime)
    COMP_COUNT = Column(Integer)
    CONFIDENTIAL_DATE = Column(DateTime)
    CORE_COUNT = Column(Integer)
    COUNTRY = Column(String)
    CURRENT_CLASS = Column(String)
    CURRENT_STATUS = Column(String)
    CURRENT_STATUS_DATE = Column(DateTime)
    DATA_SOURCE = Column(String)
    DATUM = Column(String)
    DIR_SRVY_COUNT = Column(Integer)
    DRILL_RIG_NUM = Column(String)
    DRILL_TD = Column(Float)
    DST_COUNT = Column(Integer)
    FINAL_DRILL_DATE = Column(DateTime)
    FINAL_TD = Column(Float)
    GROUND_ELEV = Column(Float)
    IPTS_COUNT = Column(Integer)
    KB_ELEV = Column(Float)
    LAST_INJECTION_DATE = Column(DateTime)
    LAST_PRODUCTION_DATE = Column(DateTime)
    LEASE = Column(String)
    LICENSEE = Column(String)
    LICENSE_DATE = Column(DateTime)
    LICENSE_NUMBER = Column(String)
    LOG_COUNT = Column(Integer)
    MAX_TVD = Column(Float)
    OLDEST_STRAT_AGE = Column(String)
    OLDEST_STRAT_UNIT_ID = Column(String)
    ON_INJECTION_DATE = Column(DateTime)
    ON_PRODUCTION_DATE = Column(DateTime)
    OPERATOR = Column(String)
    OPERATOR_ABBREVIATION = Column(String)
    PARENT_RELATIONSHIP_TYPE = Column(String)
    PARENT_UWI = Column(String)
    PLOT_SYMBOL = Column(String)
    POOL = Column(String)
    PPDM_GUID = Column(String)
    PRODUCING_HORIZON = Column(String)
    PRODUCING_STATUS = Column(String)
    PRODUCING_STRAT_AGE = Column(String)
    PROFILE_TYPE = Column(String)
    PROSPECT_NAME = Column(String)
    PROVINCE_STATE = Column(String)
    REGION = Column(String)
    REMARK = Column(String)
    RIG_RELEASE_DATE = Column(DateTime)
    SITUATION = Column(String)
    SPUD_DATE = Column(DateTime)
    STATUS_TYPE = Column(String)
    SURFACE_LATITUDE = Column(Float)
    SURFACE_LOC_QUALITY = Column(String)
    SURFACE_LONGITUDE = Column(Float)
    SURFACE_UWI = Column(String)
    SURVEY_GRID = Column(String)
    SU_COUNT = Column(Integer)
    TD_FORMATION = Column(String)
    TD_STRAT_AGE = Column(String)
    TD_STRAT_NAME_SET_ID = Column(String)
    TD_STRAT_UNIT_ID = Column(String)
    VEL_SRVY_COUNT = Column(Integer)
    WATER_DEPTH = Column(Float)
    WATER_DEPTH_DATUM = Column(String)
    WELL_NAME = Column(String)
    WELL_NUMBER = Column(String)
    WELL_NUMERIC_ID = Column(Integer)
    WELL_TYPE = Column(String)
    ROW_CHANGED_DATE = Column(DateTime)
    
    pekerjaan = relationship('Pekerjaan', back_populates='well')

